### ISSUE TITLE
Link back to original "resource" repos instead of forks

### ISSUE THREAD

**Issue by markerikson** [nitin42/React-Q-As#1]
Hi. While I appreciate all efforts to help document the React ecosystem, I have a philosophical complaint about the "Awesome resources" links you have listed.

It appears that you've forked each of the listed repos, and are linking to your forks instead of the originals.  That's certainly permissible legally, technically, and conceptually, but _why_ are you doing that?

In particular, I've spent a lot of time and effort building up the "React/Redux Links" and "Redux Ecosystem Links" repos.  I update them on a weekly basis.  When you link to your forks instead of my original repos, readers are losing out on the ongoing improvements I'm making to those lists.  Same goes for the other resource lists, as well as the Redux repo itself.

This isn't any kind of shutdown threat or anything, but I _would_ encourage you to link to the original repos instead of the forks.

**Comment by nitin42** [comment]
I am really sorry for that. I made a terrible mistake. I just forget to open the originals ones and instead copied the links for my forks. ! Won't let it happen again and I really appreciate your hard work for this AWESOME (10x) list. Your list is the reason I was able to learn React in a very captivating way and I shared this resource further in the community. Inspired by your list I am also doing the same thing. Giving back to the community and not puncturing the equilibrium.

**Comment by nitin42** [comment]
Changes done!

**Comment by markerikson** [comment]
Cool, thanks!

**Comment by nitin42** [comment]
Give it a star would make a day for me!
